//
// Copyright 2026 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#ifndef PXR_USD_IMAGING_USD_IMAGING_SMILEY_API_H
#define PXR_USD_IMAGING_USD_IMAGING_SMILEY_API_H

#include "pxr/base/arch/export.h"

#if defined(PXR_STATIC)
#   define USDIMAGINGSMILEY_API
#   define USDIMAGINGSMILEY_API_TYPE
#   define USDIMAGINGSMILEY_API_TEMPLATE_CLASS(...)
#   define USDIMAGINGSMILEY_API_TEMPLATE_STRUCT(...)
#   define USDIMAGINGSMILEY_LOCAL
#else
#   if defined(USDIMAGINGSMILEY_EXPORTS)
#       define USDIMAGINGSMILEY_API ARCH_EXPORT
#       define USDIMAGINGSMILEY_API_TYPE ARCH_EXPORT_TYPE
#       define USDIMAGINGSMILEY_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#       define USDIMAGINGSMILEY_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#   else
#       define USDIMAGINGSMILEY_API ARCH_IMPORT
#       define USDIMAGINGSMILEY_API_TYPE
#       define USDIMAGINGSMILEY_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#       define USDIMAGINGSMILEY_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#   endif
#   define USDIMAGINGSMILEY_LOCAL ARCH_HIDDEN
#endif

#endif
